linters:
  enable:
    - govet
    - gofmt
    - gosec
    - revive
issues:
  exclude-files:
    - "secretstream/secretstream.go" 
    - "secretstream/secretstream_test.go" 
linters-settings:
  errcheck:
    exclude-functions:
      - (*io.PipeReader).CloseWithError
      - (*io.PipeWriter).CloseWithError
      - encoding/binary.Write(*bytes.Buffer)
      - (*github.com/spf13/cobra.Command).Help
      - (*os.Process).Kill
  gosec:
    excludes:
      - G204
      - G306
  revive:
    rules:
      - name: indent-error-flow
        disabled: true
