project_name: uback

builds:
  - id: uback
    ldflags:
      - -s -w -X github.com/sloonz/uback/cmd.tag={{.Tag}} -X github.com/sloonz/uback/cmd.commit={{.ShortCommit}} -X github.com/sloonz/uback/cmd.buildDate={{.Date}}
    binary: uback
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux

archives:
  - id: uback
    wrap_in_directory: true
    builds:
      - uback
    files:
      - LICENSE
      - README.md
      - doc
source:
  enabled: true

changelog:
  sort: asc
  filters:
    exclude:
      - chlg skip
      - ci skip
      - typo
      - minor
      - Merge pull request
      - Merge branch
      - "test:"
      - "build:"
      - "chore:"
